In [ ]:


import numpy as np 
import pandas as pd 



import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [ ]:
# IBRAHIM SULTAN
# TASK 3 CAR PRICE PREDICTION WITH MACHINE LEARNING
# OASIS INFOBYTE

# Car Sales Data Analysis project

### Import packags

In [ ]:
import pandas as pd , os , plotly.express as px,numpy as np

### Reading Data Frames

In [ ]:
df = pd.read_csv("/kaggle/input/car-prices-market/used_car_prices.csv")
df1 = pd.read_csv("/kaggle/input/car-prices-market/new_cars_prices.csv")

### Getting some information about the Data

In [ ]:
df.shape

In [ ]:
df.info()

In [ ]:
df.isnull().sum()

In [ ]:
df.nunique()

### Handling Duplicats and null values

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
null_values =df[df['Average price'].isnull()]
null_values.sample(5)

In [ ]:
df.drop(null_values.index , inplace=True)

df.reset_index(drop=True).sample(3)

df.shape

### Getting Some Examples from column "Car Model" for cleaning

In [ ]:
df['Car Model'].sample(5,random_state=25)

In [ ]:
df['Car Brand'] = df['Car Model'].apply(lambda i:"".join(i.split(" ")[0]))
df['Car_Model_Name'] = df['Car Model'].apply(lambda i:" ".join(i.split(" ")[1:-1]))
df['Car_Model_Year'] = df['Car Model'].apply(lambda i:"".join(i.split(" ")[-1]))

In [ ]:
df.sample(5)

### Getting Some Examples of Numerical columns for cleaning

In [ ]:
df[['Average price','Minimum price','Maximum price']].sample(5)

### Creating a function to change the amounts to numerical Values

In [ ]:
def change_price_to_numeric(r):
    return float(("".join(r.split(" ")[0])).replace(",",""))

In [ ]:
df['Average price'] = df['Average price'].astype(str).apply(change_price_to_numeric)
df['Minimum price'] = df['Minimum price'].astype(str).apply(change_price_to_numeric)
df['Maximum price'] = df['Maximum price'].astype(str).apply(change_price_to_numeric)

### Getting Samples

In [ ]:
df[['Average price','Minimum price','Maximum price']].sample(3)

### Detecting Outliars if there is any

In [ ]:
df_numerical = df.select_dtypes(include="number")

In [ ]:
for i in df_numerical.columns:
    fig= px.violin(df_numerical,i)
    fig.show()

### Handling Datetime objects

In [ ]:
df['Month/Year'].sample(3)

df['Month/Year'] = pd.to_datetime(df['Month/Year'],errors="coerce")
df['Month'] = df['Month/Year'].dt.month_name()
df['Month_Num'] = df['Month/Year'].dt.month
df['Quarter'] = df['Month/Year'].dt.quarter.astype(str).apply(lambda r:r.split(".")[0])
df['Year'] = df['Month/Year'].dt.year.astype(str).apply(lambda r:r.split(".")[0])

In [ ]:
df[['Month','Quarter','Year','Month_Num']].sample(3)

### Checking the Data again after cleaning

In [ ]:
df.info()

In [ ]:
df.columns

### Top 10 Sold Used Cars by Years

In [ ]:
top_10_sold_cars_by_count_and_year =pd.pivot_table(df,index="Car Brand",columns="Year",values="Average price",aggfunc=len,fill_value=0,margins=True,margins_name="Total Sold Cars").sort_values(by="Total Sold Cars",ascending=False).head(11)[1:]

top_10_sold_cars_by_count_and_year

In [ ]:
for i in top_10_sold_cars_by_count_and_year.columns:
    fig = px.line(top_10_sold_cars_by_count_and_year,y=i,text=i)
    fig.show()

In [ ]:
df['Year'].value_counts()

## Insights for the above Charts:
#### 1- "Hyundi" is dominating the used car market in all years
#### 2- "Chevrolet" & "Daewoo" had more sold used cars than Kia between (2012 & 2015)
#### 3- Most Sold Used Cars was in 2022
#### 4- Decreasing in sold  Used cars in 2020 possible cause (Covid-19)

###

### Top 10 Sold Cars in Total

In [ ]:
top_10_Brand_sold_cars=df.groupby("Car Brand")['Year'].count().to_frame().sort_values(by="Year",ascending=False).reset_index().head(10)

px.bar(data_frame=top_10_Brand_sold_cars,x="Car Brand",y="Year",text_auto=True)

### Top 10 Amount of sales by Average Price by Years

In [ ]:
top_10_sold_cars_by_highest_sales_of_Average_price =pd.pivot_table(df,index="Car Brand",columns='Year',values="Average price",aggfunc=sum,fill_value=0,margins=True,margins_name="Total_Sales_Amount").sort_values(by="Total_Sales_Amount",ascending=False).head(11)[1:].round(0)

top_10_sold_cars_by_highest_sales_of_Average_price

In [ ]:
for i in top_10_sold_cars_by_highest_sales_of_Average_price.columns:
    fig = px.line(data_frame=top_10_sold_cars_by_highest_sales_of_Average_price,y=i,text=i)
    fig.show()

In [ ]:
df.groupby(['Year',"Car Brand"]).agg({'Average price':"sum","Car Model":'count'}).reset_index().sort_values(by=["Average price"],ascending = False).head(20)

## Insights for the above Charts: 

#### 1- Hyundai is on the top of the sales of used cars

#### 2- Year 2022 had the Highest amounts of sales

#### 3- Mercedes exceeded Sales amounts of Hyundai in (2021 & 2022)

####

### Total 10 Amount of sales by Average Price

In [ ]:
dfg= df.groupby("Car Brand")["Average price"].sum().to_frame().sort_values(by="Average price",ascending=False).head(10).reset_index()

px.histogram(dfg,x="Car Brand",y="Average price",text_auto=True).update_xaxes(categoryorder= "total descending")

### TOP 10 Models Sold

In [ ]:
dfg_1 = df.groupby(['Car_Model_Name'])['Car Model'].count().to_frame().reset_index().sort_values(by="Car Model",ascending=False).head(10)

px.bar(dfg_1,x="Car_Model_Name",y="Car Model",text_auto=True,text="Car Model")

### Total Sold Used Cars By Months

In [ ]:
dfg_2=df.groupby(['Month',"Month_Num"])['Car Model'].count().to_frame().reset_index().sort_values(by="Month_Num",ascending=True)

px.bar(dfg_2,x="Month",y="Car Model",text="Car Model")

### Total Sold Used Cars By Quarter

In [ ]:
dfg_2=df.groupby(['Quarter'])['Car Model'].count().to_frame().reset_index().sort_values(by="Quarter",ascending=True)

px.bar(dfg_2,x="Quarter",y="Car Model",text_auto=True)

####

### Percentage of sales by Years

In [ ]:
dfg_3=df.groupby("Year").count()['Car Brand'].to_frame().reset_index().sort_values(by="Year",ascending=True)

px.pie(dfg_3,names="Year",values="Car Brand",title="Percentage of sales by Years")

### Total Count of sold Used Cars by Years

In [ ]:
dfg_4=df.groupby(['Year'])['Car Model'].count().to_frame().reset_index().sort_values(by="Year",ascending=False)

px.bar(dfg_4,x="Year",y="Car Model",text="Car Model",labels=True)

### New Cars DataFrame

In [ ]:
df1.info()

In [ ]:
df1.drop_duplicates(inplace=True)

df1.reset_index(drop=True)

In [ ]:
def transmission_type(d):
    lis_= ["Manual","M/T"," MT","manual"]
    if any(x in d for x in lis_):
        return "Manual"
    else:
        return "Automtic"

In [ ]:
df1['Transmission_type'] = df1['Car Model'].apply(transmission_type)
df1['Transmission_type'].value_counts()

In [ ]:
df1["Car Brand"] = df1['Car Model'].apply(lambda x:"".join(x.split()[0]))
df1["Car_Model_Year"] = df1['Car Model'].apply(lambda x:"".join(x.split()[-1]))

In [ ]:
df1[['Car Brand',"Car_Model_Year"]]

In [ ]:
df1['Car_Brand_Description'] = df1['Car Model'].apply(lambda x:" ".join(x.split()[1:-1]))

df1['Car_Brand_Description'].head(5).to_list()

In [ ]:
def car_model_description(car):
    lis = ['Automatic',"Automotic","Automtic","A/T/","A/T","A/T ","M/T","manual","Manual‏","manual‏","A/T","/","M/T/","Manual","AT-6DCT","AT","اتوماتيك"]
    dict_ = {"High line":"Highline","Base Line":"Baseline","High Line":"Highline","Top Line":"Topline"}
    for i in car:
        lis_1= car.split(" ")
        lis_2= [i for i in lis_1 if i not in lis]   
        for i in range(len(lis_2)):
            if lis_2[i] in dict_:
                lis_2[i] = dict_[lis_2[i]]
            lis_3= " ".join(lis_2)
            return lis_3

In [ ]:
df1['Car_Brand_Description'] = df1['Car_Brand_Description'].apply(car_model_description)

In [ ]:
df1['Car_Brand_Type'] = df1['Car_Brand_Description'].apply(lambda r:r.split(" ")[0])

In [ ]:
df1['Car_Brand_Type'] = df1["Car Brand"] + " " + df1['Car_Brand_Type']

In [ ]:
df1['Car_Brand_Type'].value_counts().to_frame().reset_index().sort_values(by="Car_Brand_Type",ascending=False).head(10)

In [ ]:
df1[["Old Price","Price Change","New Price"]].head(5)

In [ ]:
df1['Old Price']= df1['Old Price'].apply(lambda r:r[:-4].replace(',',"")).astype("float")

df1['New Price']= df1['New Price'].apply(lambda r:r[:-4].replace(',',"")).astype("float")

df1['Price Change'] = df1['New Price'] - df1['Old Price']

In [ ]:
df1['Price Change']

In [ ]:
df1['date_range']=pd.to_datetime(df1['date_range'],format="%d/%m/%Y",errors="coerce")

df1['Month'] = df1['date_range'].dt.month_name()
df1['Month_Num'] = df1['date_range'].dt.month
df1['Quarter'] = df1['date_range'].dt.quarter.astype(str).apply(lambda r:r.split(".")[0])
df1['Year'] = df1['date_range'].dt.year.astype(str).apply(lambda r:r.split(".")[0])

In [ ]:
df1.info()

In [ ]:
df1.head(5)